<?php

namespace AppBundle\Repository;

/**
 * Ot_estadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Ot_estadoRepository extends \Doctrine\ORM\EntityRepository
{
}
