<?php

namespace AppBundle\Repository;

/**
 * Ot_trabajoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Ot_trabajoRepository extends \Doctrine\ORM\EntityRepository
{
}
