<?php

namespace AppBundle\Repository;

/**
 * TrabajosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrabajosRepository extends \Doctrine\ORM\EntityRepository
{
}
